#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ] || [ "$branch" = "develop" ]; then
  echo "You can't commit directly to main or develop branch"
  exit 1
fi

npm run format
npm run lint
npm run lint-staged
npm test